### ISSUE TITLE
Strange issues encountered by JETI in testing current and temperature

### ISSUE THREAD

**Issue by aepub** [mstrens/oXs_on_RP2040#91] opened 2023-07-11 15:00 UTC
During the use of OXS, there were problems with the constantly fluctuating values of the tested voltage, current, consumption capacity, temperature, etc. Initially, it was thought that the interference caused by the interaction between the RP2040 ZREO module and other peripheral accessories was the reason. Therefore, we attempted to design a PCB that integrated RP2040 chip, MP6050, MS5611, and current sensor chip ASP758-150B.

     After the production of PCBway was completed, testing was carried out, but unfortunately, the integrated PCB board also encountered the same problem. The measured values of voltage, current, temperature, etc. being tested could not display fixed data, and there was always a phenomenon of up and down deviation. The battery capacity consumed was also slowly increasing. A phenomenon similar to 'leakage' occurs.

I tested the main and test branches of OXS, as well as changing the JETI mode to exbus or UDI, and all encountered the same problem.

This is the video taken:
 https://www.youtube.com/shorts/pH-MBhFZkRk

Before using OXS, the current measurement module I used separately came from https://www.rc-thoughts.com/jeti-ampsensor/ It is very stable. Always displaying a fixed value,

This is a video from thoughts.com: 
https://www.youtube.com/watch?v=YeZIwd81hs

What is the reason for this?

**Comment by mstrens** [comment] 2023-07-11 16:11
I see 2 explanations:
- or the voltages/current/...to measured  really fluctuates
- or the power supply of the RP2040 fluctuates.
I expect that you face the second.

oXs uses the ADC (analog to digital) component from the RP2040.
The values provided by the ADC depends directly on the RP2040 Vcc voltage.
You can perhaps add capacitors to increase power supply voltage.

An alternative is to let oXs perform more conversions.
Currently the values transmitted by oXs are an average of 10 ADC conservions.
This is defined a line in voltage.h 
#define SUM_COUNT_MAX_VOLTAGE 10 // number of ADC conversions to calculate averages

You can try to increase the number of conversions for calculating an average changing the line e.g. to:
#define SUM_COUNT_MAX_VOLTAGE 100.

**Comment by mstrens** [comment] 2023-07-12 18:21
Perhaps you can make some tests to check if the jumps occurs when the data are captured or when they are transmitted.
I expect that  the jumps occurs when the data are captured.
To exclude an issue during the transmission, you can send a command FVP or FVN via USB.
Then oXs will still collect the data from the sensors but the values transmitted will be fixed predefined values.
Normally after such a command the Tx should display always the same values (no jump at all).
Note: after such a command, oXs will send fix values for all possible sensors (even those that are not defined in the configuration)

You can also use use the command FV to see the collected data on the PC display.
Entering several FV commands should give some jumps in the values on the PC if the issue is in the process of collecting the data from the sensors. 

About GPS: please note that by default, I think that oXs configure the GPS in order to get data at a frequency of 10Hz. At such a high frequency, it is probably not abnormal that GPS data fluctuates specially when GPS does not have a clear view of the satellites (e.g. when GPS is indoor)

**Comment by mstrens** [comment] 2023-07-13 07:23
ADC has a resolution of 12 bits = 4096 steps.
So if you use a voltage divider that allows to measure max 20 volt (as example), it means that ideally the ADC can provide a value with an error of 20000mv/4096 = 5mv.
In the RP2040, it is said that the error can sometime be 8 X bigger => 40mv.
200mv seems quite big.

The error is perhaps because there is only one ADC shared by 4 analog inputs. Perhaps that when I switch from one input to another one I have to wait some time before asking for the conversion (to let the voltage stabilize on the internal capacitor).
There is an easy way to test if this could be the reason of the issue.
If you measure only one voltage (or current), there will be no need for the ADC to switch from one input to another.
Could you make a test where you change the configuration in order to ask only e.g. for VOLT1 (so disabling VOLT2, VOLT3, VOLT4 pins).
If this is a solution, I could change the code in order to have more time between selecting the analog pin and performing the conversion.

**Comment by mstrens** [comment] 2023-07-14 15:34
In the video, Volt1 is quite stable.
It is strange that Temp changes.
I put on github a new version where 
- I ask 3 conversions instead of 1 each time I switch from one pin to another one.
- I use only the 2 last to calculate the value
- I calculate the average on 30 iterations (instead of 10)
So each telemetry value uses 60 measurements.
-

**Comment by mstrens** [comment] 2023-07-15 06:10
Indeed, I multiplied by 2 instead of dividing by 4.
I fix it in new version on github
Otherwise, it seems better.

**Comment by mstrens** [comment] 2023-07-15 16:26
I suggest that you plot the real values and the oXs values in a chart (for the current).
You will see that there is a linear relation between the 2 set of datas. I did it in XLS.
So, if you change the offset and the scale oXs parameters (for current), you will get realistic values on the Tx display.

**Comment by mstrens** [comment] 2023-07-16 08:12
I will try to explain it but first, could you
- set offset = 0 and scale = 1 for Volt2 in the oXs parameter
- perform the same test for 0, 1, 2, ...10A and gives the values you get on remote control (or provided by FV command) for each current
- say if you have excel.

**Closed as completed** 2023-07-19 04:16 UTC
